import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

import Navbar from '../components/Navbar'
import Parent from '../components/Parent'
import MainPage from '../components/MainPage'
import Video from '../components/Video'
import Skills from '../components/Skills'
import Contact from '../components/Contact'
import Projects from '../components/Projects'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>MrunalV | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPage/>
      
      <Skills/>
      <Projects/>
      <Contact/>
      
      
      
 


    </>
  )
}
